name: Deploy to github pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - website/**
      - .github/workflows/gh-pages-deployment.yml
jobs:
  ci-cd:
    runs-on: ubuntu-latest
    name: Deploy
    permissions:
      contents: write
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          folder: website

          